version: '3.4'

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432

  pgweb:
    restart: on-failure
    depends_on:
      - db
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    environment:
      - DATABASE_URL=postgres://postgres:root@db:5432/postgres?sslmode=disable